In [2]:
import numpy as np

In [2]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [3]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.39527791, 0.72799322, 0.69864237, 0.1311751 , 0.08502225])

In [15]:
np.random.randn(10)

array([ 1.74123549, -2.30862399,  0.96331114, -0.92218162,  0.02841511,
        1.95073805,  0.79133561,  0.55842015, -0.54095318, -1.26593848])

In [10]:
a=np.arange(1,26).reshape(5,5)

In [11]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [17]:
a[3,2]

18

In [20]:
a[:,2:3]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23]])